# Generated by Django 5.2.4 on 2025-09-03 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bull', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Bull.sequence'),
        ),
    ]
