# Generated by Django 5.2.4 on 2025-09-03 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bull', '0002_discipline_sequence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletin',
            name='term',
        ),
        migrations.AddField(
            model_name='bulletin',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='Bull.classroom'),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletin',
            name='sequence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='Bull.sequence'),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='Bull.student'),
        ),
    ]
