# Generated by Django 5.2.4 on 2025-09-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bull', '0003_remove_bulletin_term_bulletin_average_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Canevas bulletin', max_length=100)),
                ('header_docx', models.FileField(blank=True, null=True, upload_to='bulletin_templates/headers/')),
                ('footer_docx', models.FileField(blank=True, null=True, upload_to='bulletin_templates/footers/')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_templates', to='Bull.schoolyear')),
            ],
        ),
    ]
