# Generated by Django 5.2.4 on 2025-09-05 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bull', '0004_bulletintemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('min_heures_absence', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='discipline',
            name='sanctions_text',
        ),
        migrations.AddField(
            model_name='discipline',
            name='sanction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bull.sanction'),
        ),
    ]
