# Generated by Django 5.2.4 on 2025-09-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bull', '0005_sanction_remove_discipline_sanctions_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletintemplate',
            name='html_canvas',
            field=models.TextField(blank=True, help_text='Canevas HTML personnalisé (entête, pied, images, etc.)', null=True),
        ),
    ]
