# Generated by Django 5.2.4 on 2025-10-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bull', '0006_bulletintemplate_html_canvas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
